seed: [1234] #, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243]

data:
  dataset: uji
  params:
    val: 0.1

    # grid encoding
    grid_size: 30
    padding_ratio: 0.3

    #min_max, standard, powed
    scaling: powed

    # ground truth construction for OGC
    class_pad: True
    reg_pad: True
    weighted_grid_labels: False

models:

 # SHL backbone

  - name: mCEL
    type: mCEL
    backbone:
      type: MLP
      layers: [ 512, 512 ]
      dropout: 0.5
      activation: relu
    head:
      classification:
        type: MLP
        layers: [256]
        dropout: 0.25
        activation: relu
      regression:
        type: MLP
        layers: [256]
        dropout: 0.25
        activation: relu
    params:
      epochs: 20
      batch_size: 32
      lr: 0.0005
      verbose: 0

## 2D CNN backbone
#
#  - name: OGC_CNN
#    pretrained: True
#    type: MHC
#    backbone:
#      type: CNN
#      input_image: TPAI
#      layers: [ 64, 64 ]
#      kernel: [3, 3]
#      dropout: 0.5
#      activation: relu
#    head:
#      classification:
#        type: MLP
#        layers: [256]
#        dropout: 0.25
#        activation: relu
#      regression:
#        type: MLP
#        layers: [256]
#        dropout: 0.25
#        activation: relu
#    params:
#      epochs: 20
#      lr: 0.0005

dir:
  base: exp/uji/mCEL/
  result_file: metrics.pickle

